package ca.en.solution.history;

import java.io.IOException;
import java.io.InputStream;
import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.core.io.Resource;
import org.springframework.stereotype.Component;

import tools.jackson.core.type.TypeReference;
import tools.jackson.databind.json.JsonMapper;

/** Reads the optional fixture generated by backend/fixtures/generate-history.mjs. */
@Component
public class FileHistoryRepository implements HistoryRepository {

    private final Map<String, List<PerformanceSnapshot>> histories;

    public FileHistoryRepository(JsonMapper jsonMapper,
            @Value("${history.file:file:../fixtures/performance-history.json}") Resource historyFile) throws IOException {
        if (!historyFile.exists()) {
            histories = Map.of();
            return;
        }
        try (InputStream input = historyFile.getInputStream()) {
            histories = jsonMapper.readValue(input, new TypeReference<Map<String, List<PerformanceSnapshot>>>() {
            });
        }
    }

    @Override
    public List<PerformanceSnapshot> historyOf(String portfolioId) {
        return histories.getOrDefault(portfolioId, List.of());
    }
}
